spring:
  application:
    name: cineapp
  profiles:
    active: prod
  datasource:
# Local deploy  
#    url: jdbc:mysql://localhost:3306/cineapp?useSSL=false
#    username: admin
#    password: admin
# Prod deploy
    url: jdbc:mysql://movies-service-db.cdxbqdojlywk.us-east-1.rds.amazonaws.com:3306/cineapp?useSSL=false
    username: admixxx
    password: admixxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    
  jackson:
    date-format: yyyy-MM-dd
server:
  port: 8080
  
aws:
  s3:
    bucketName: uploadmodernized
    accessKey: xxx
    secretKey: xxx
    token: xxx
    region: us-east-1
